version: "3.9"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3.10 manage.py runserver 0.0.0.0:2087
    volumes:
      - .:/code
    ports:
      - "2087:2087"
    depends_on:
      - db